spring:
  profiles:
     active: dev

---
# spring配置
spring:
  profiles: dev
  application:
     name: SPRING-CLOUD 

# Eureka的配置
eureka:
  client:
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/

---

# spring配置
spring:
  profiles: test
  application:
     name: SPRING-CLOUD 

# Eureka的配置
eureka:
  client:
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
