# 服务提供者(微服务)的相关配置
spring:
  profiles:
     active: dev

---
server:
   port: 8201

# spring配置
spring:
  profiles: dev
  application:
     name: SPRING-CLOUD 

# Eureka的配置
eureka:
  client:
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/

---
server:
   port: 8202
# spring配置
spring:
  profiles: test
  application:
     name: SPRING-CLOUD 

# Eureka的配置
eureka:
  client:
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
