spring:
  profiles:
    active: dev
---
server:
  port: 8081

# mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.kuang.springcloud.pojo
  mapper-location: classpath:mybatis/mapper/*.xml

# spring配置
spring:
  application:
     name: springcloud-config-dept
  profiles: dev
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource # 数据源
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/db03?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=True&characterEncoding=utf-8
     username: root
     password: 123456

# Eureka的配置
eureka:
  client:
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: springcloud-provider-dept8081 # eureka上服务的默认信息
    prefer-ip-address: true # 选择服务时左下角显示ip地址不是域名

info:
  app.name: kuangshen-springcloud
  company.name: blog.kuangstudy.com
---
server:
  port: 8081

# mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.kuang.springcloud.pojo
  mapper-location: classpath:mybatis/mapper/*.xml

# spring配置
spring:
  application:
     name: springcloud-config-dept
  profiles: test
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource # 数据源
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/db02?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=True&characterEncoding=utf-8
     username: root
     password: 123456

# Eureka的配置
eureka:
  client:
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: springcloud-provider-dept8081 # eureka上服务的默认信息
    prefer-ip-address: true # 选择服务时左下角显示ip地址不是域名

info:
  app.name: kuangshen-springcloud
  company.name: blog.kuangstudy.com

